name: Mac Build

on:
  push:
    branches: [ "master", "main", "feature/*" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master", "main", "feature/*" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update || true
        brew install libpng boost-python3 qt@5 lemon flex ninja cmake dylibbundler

    - name: Build Antimony and Create DMG
      run: |
        chmod +x scripts/build-mac.sh scripts/bundle-mac.sh
        ./scripts/build-mac.sh --dmg --skip-deps

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: antimony-mac.dmg
        path: antimony-mac.dmg

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: antimony-mac.dmg
