name: Mac Build

on:
  push:
    branches: [ "master", "main", "feature/*" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master", "main", "feature/*" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update || true
        brew install libpng python@3.11 boost-python3 qt@5 lemon flex ninja cmake

    - name: Build Antimony
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_PREFIX_PATH=$(brew --prefix qt@5) -GNinja ..
        ninja

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: antimony-mac-build
        path: build/app/Antimony.app

    - name: Zip Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd build/app
        zip -r ../../antimony-mac.zip Antimony.app

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: antimony-mac.zip
